name: 'Setup .NET Core SDK'
description: 'Set up a specific version of the .NET Core SDK and add the command-line tools to the PATH'
author: 'GitHub'
inputs: 
  dotnet-version:
    description: 'SDK version to use. Example: 2.2.104'
# Deprecated option, do not use. Will not be supported after October 1, 2019
  version:
    description: 'Deprecated. Use dotnet-version instead. Will not be supported after October 1, 2019'
    deprecationMessage: 'The version property will not be supported after October 1, 2019. Use dotnet-version instead'
runs:
  using: 'node12'
  main: 'lib/setup-dotnet.js'
